"""Dhan adapter: ratified normalisation and SDK isolation, without a network.

The payloads driving these tests come from ``tests/fixtures/dhan_ticker_payloads.json``,
which is generated by packing Dhan's documented binary layouts and running them
through the installed SDK's own ``process_data()`` — so the shape under test is
the SDK's, not something hand-written to match the implementation. Block 2
replaces that fixture with payloads captured from a real connection.

Three Phase 1 defects are pinned here so they cannot regress: the time-only
``LTT``, the non-existent ``last_quantity`` key, and non-dict frames being
miscounted as malformed.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

from common.market_data.dhan import (
    DISCONNECT_REASONS,
    DISCONNECT_TOKEN_EXPIRED,
    DhanFeedError,
    DhanMarketFeedAdapter,
    reconstruct_exchange_time,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE = REPO_ROOT / "tests" / "fixtures" / "dhan_ticker_payloads.json"


def _fixture_frames() -> dict[str, list[dict[str, Any]]]:
    data = json.loads(FIXTURE.read_text(encoding="utf-8"))
    grouped: dict[str, list[dict[str, Any]]] = {}
    for frame in data["frames"]:
        grouped.setdefault(frame["label"], []).append(frame["payload"])
    return grouped


FRAMES = _fixture_frames()


def _adapter(**kwargs: Any) -> DhanMarketFeedAdapter:
    return DhanMarketFeedAdapter(
        client_id="test-client",
        access_token="test-token",
        instrument_label="NIFTY",
        **kwargs,
    )


# ------------------------------------------------------------ construction
def test_missing_credentials_are_refused_at_construction():
    with pytest.raises(DhanFeedError, match="client id and an access token"):
        DhanMarketFeedAdapter(client_id="", access_token="token")


def test_starting_without_a_subscription_is_refused():
    with pytest.raises(DhanFeedError, match="no subscriptions"):
        _adapter().start(lambda tick: None)


def test_subscriptions_are_a_union_not_a_list():
    adapter = _adapter()
    adapter.subscribe(["1", "2"])
    adapter.subscribe(["2", "3"])
    assert adapter.subscribed == {"1", "2", "3"}


def test_stopping_an_unstarted_adapter_is_safe():
    _adapter().stop()  # must not raise


# ------------------------------------------------- the fixture's real shape
def test_the_fixture_carries_the_sdk_shape_not_a_guess():
    """Guards the assumptions every other test here rests on.

    If a future SDK changes these, this test fails loudly instead of the
    normalisation quietly producing wrong ticks.
    """
    ticker = FRAMES["ticker"][0]
    assert ticker["type"] == "Ticker Data"
    assert isinstance(ticker["LTP"], str), "LTP is a formatted string, not a float"
    assert isinstance(ticker["security_id"], int), "security_id is an int, not a str"
    assert isinstance(ticker["LTT"], str) and len(ticker["LTT"]) == 8, "LTT is HH:MM:SS"
    assert "last_quantity" not in ticker, "Phase 1 read a key that does not exist"
    assert "LTQ" not in ticker, "quantity is Quote-only"
    assert "LTQ" in FRAMES["quote"][0], "Quote Data does carry LTQ"


def test_a_ticker_frame_becomes_a_tick():
    adapter = _adapter()
    tick = adapter.normalise(FRAMES["ticker"][0])

    assert tick is not None
    assert tick.security_id == "49081"
    assert tick.last_price == pytest.approx(187.45)
    assert tick.instrument == "NIFTY"
    assert tick.exchange_time.tzinfo is not None
    assert adapter.counters.ticks == 1


def test_a_quote_frame_supplies_the_quantity_from_ltq():
    """Defect 2: Phase 1 read ``last_quantity``, which no frame contains, so live
    candle volume was always zero."""
    adapter = _adapter()
    tick = adapter.normalise(FRAMES["quote"][0])

    assert tick is not None
    assert tick.last_quantity == 75
    assert adapter.counters.ticks == 1


def test_per_instrument_labels_are_applied():
    adapter = _adapter(instrument_labels={"13": "NIFTY", "49081": "NIFTY24JUL25000CE"})
    assert adapter.normalise(FRAMES["ticker"][0]).instrument == "NIFTY24JUL25000CE"  # type: ignore[union-attr]
    assert adapter.normalise(FRAMES["ticker"][3]).instrument == "NIFTY"  # type: ignore[union-attr]


# ------------------------------------------------------- exchange timestamps
def test_the_time_only_ltt_is_reconstructed_and_not_a_fallback():
    """Defect 1, the most consequential one.

    ``LTT`` is ``strftime('%H:%M:%S')`` against UTC — no date. Phase 1 passed it
    to ``datetime.fromisoformat``, which raises, so *every* tick silently fell
    back to receipt time and candles were bucketed by arrival rather than by
    exchange time. That is precisely the opposite of the aggregator's contract.
    """
    adapter = _adapter()
    tick = adapter.normalise(FRAMES["ticker"][0])

    assert tick is not None
    assert tick.exchange_time.strftime("%H:%M:%S") == FRAMES["ticker"][0]["LTT"]
    assert tick.exchange_time != tick.received_at
    assert adapter.counters.exchange_time_fallbacks == 0
    assert adapter.counters.fallback_ratio == 0.0


def test_ltt_picks_the_date_closest_to_receipt():
    received = datetime(2026, 7, 30, 8, 35, 10, tzinfo=UTC)
    moment = reconstruct_exchange_time("08:35:03", received)
    assert moment == datetime(2026, 7, 30, 8, 35, 3, tzinfo=UTC)


def test_ltt_just_before_utc_midnight_resolves_to_the_previous_day():
    """A rollover guard. It cannot arise for Indian equity/F&O — that session is
    03:45-10:00 UTC — but it costs nothing and does not assume other segments
    keep that property."""
    received = datetime(2026, 7, 31, 0, 0, 5, tzinfo=UTC)
    moment = reconstruct_exchange_time("23:59:58", received)
    assert moment == datetime(2026, 7, 30, 23, 59, 58, tzinfo=UTC)


def test_ltt_just_after_utc_midnight_resolves_to_the_next_day():
    received = datetime(2026, 7, 30, 23, 59, 58, tzinfo=UTC)
    moment = reconstruct_exchange_time("00:00:03", received)
    assert moment == datetime(2026, 7, 31, 0, 0, 3, tzinfo=UTC)


def test_an_epoch_timestamp_is_still_accepted():
    """Most likely future SDK change; accepted so it would not be a silent
    fallback."""
    moment = reconstruct_exchange_time(1_785_400_503, datetime.now(UTC))
    assert moment == datetime.fromtimestamp(1_785_400_503, tz=UTC)


def test_an_iso_timestamp_is_still_accepted():
    moment = reconstruct_exchange_time("2026-07-30T08:35:03+00:00", datetime.now(UTC))
    assert moment == datetime(2026, 7, 30, 8, 35, 3, tzinfo=UTC)


def test_a_naive_iso_timestamp_is_assumed_utc():
    moment = reconstruct_exchange_time("2026-07-30T08:35:03", datetime.now(UTC))
    assert moment == datetime(2026, 7, 30, 8, 35, 3, tzinfo=UTC)


@pytest.mark.parametrize("raw", [None, "", "   ", "garbage", "25:99:99", 0, -1, True, False])
def test_an_unusable_timestamp_yields_none_so_the_caller_can_count_it(raw: object):
    """Epoch 0 is "no trade yet on this instrument", not 1970."""
    assert reconstruct_exchange_time(raw, datetime.now(UTC)) is None


def test_a_missing_timestamp_falls_back_to_receipt_and_is_counted():
    adapter = _adapter()
    tick = adapter.normalise({"type": "Ticker Data", "security_id": "13", "LTP": "100.0"})

    assert tick is not None
    assert tick.exchange_time == tick.received_at
    assert adapter.counters.exchange_time_fallbacks == 1
    assert adapter.counters.fallback_ratio == 1.0, (
        "a 100% fallback rate is what Phase 1 had and could not see"
    )


def test_an_instrument_with_no_trades_yet_is_rejected_outright():
    """An LTT of epoch 0 renders as "00:00:00", and its LTP is not a trade price.

    Three behaviours were possible and only one is defensible. Reconstructing it
    as a real midnight UTC would emit a tick timestamped 05:30 IST — harmless
    only by luck, because the aggregator's session filter happens to drop it.
    Substituting receipt time would be worse: the non-price would land in the
    current candle. Rejecting it upholds the spec's rule that a stale price is
    never treated as a fresh unchanged price.
    """
    adapter = _adapter()
    assert adapter.normalise(FRAMES["ticker_no_trade_yet"][0]) is None
    assert adapter.counters.untraded_frames == 1
    assert adapter.counters.ticks == 0
    assert adapter.counters.malformed_payloads == 0, "not traded is not malformed"
    assert adapter.counters.exchange_time_fallbacks == 0


def test_a_numeric_zero_ltt_is_also_treated_as_never_traded():
    adapter = _adapter()
    payload = {"type": "Ticker Data", "security_id": "49082", "LTP": "0.05", "LTT": 0}
    assert adapter.normalise(payload) is None
    assert adapter.counters.untraded_frames == 1


def test_a_missing_ltt_still_falls_back_rather_than_being_rejected():
    """Absent is not the same as zero: "we do not know when this traded" is a
    legitimate fallback, whereas "it has not traded" is not a tick at all."""
    adapter = _adapter()
    tick = adapter.normalise({"type": "Ticker Data", "security_id": "13", "LTP": "100.0"})

    assert tick is not None
    assert tick.exchange_time == tick.received_at
    assert adapter.counters.untraded_frames == 0
    assert adapter.counters.exchange_time_fallbacks == 1


# ----------------------------------------------------- frame classification
def test_a_market_status_string_is_a_non_tick_not_a_malformed_payload():
    """Defect 3: ``process_status`` returns the bare string "Markets Open".

    Phase 1's ``isinstance(payload, dict)`` guard counted it as malformed, so
    ordinary traffic inflated the malformed counter and hid a genuine problem.
    """
    adapter = _adapter()
    assert adapter.normalise("Markets Open") is None
    assert adapter.counters.non_tick_frames == 1
    assert adapter.counters.malformed_payloads == 0


def test_an_empty_frame_is_counted_separately():
    """``process_data`` returns None for an unrecognised first byte, and for a
    server-disconnection frame."""
    adapter = _adapter()
    assert adapter.normalise(None) is None
    assert adapter.counters.empty_frames == 1
    assert adapter.counters.malformed_payloads == 0


@pytest.mark.parametrize("label", ["prev_close", "oi"])
def test_recognised_non_tick_frames_are_ignored_cleanly(label: str):
    adapter = _adapter()
    assert adapter.normalise(FRAMES[label][0]) is None
    assert adapter.counters.non_tick_frames == 1
    assert adapter.counters.malformed_payloads == 0
    assert adapter.counters.ticks == 0


@pytest.mark.parametrize(
    "payload",
    [
        {"type": "Ticker Data", "security_id": "13"},
        {"type": "Ticker Data", "security_id": "13", "LTP": "0.00"},
        {"type": "Ticker Data", "security_id": "", "LTP": "100.0"},
        {"type": "Ticker Data", "LTP": "100.0"},
        {"type": "Ticker Data", "security_id": "13", "LTP": "not-a-number"},
    ],
)
def test_a_genuinely_malformed_tick_is_counted_not_raised(payload: object):
    """One bad frame must not tear down the feed for every worker in the group."""
    adapter = _adapter()
    assert adapter.normalise(payload) is None
    assert adapter.counters.malformed_payloads == 1
    assert adapter.counters.ticks == 0


@pytest.mark.parametrize("payload", [42, 3.14, [1, 2], ("a",), object()])
def test_an_unexpected_payload_type_is_malformed(payload: object):
    adapter = _adapter()
    assert adapter.normalise(payload) is None
    assert adapter.counters.malformed_payloads == 1


def test_replaying_the_whole_fixture_produces_only_ticks_and_recognised_frames():
    """No frame the SDK can emit may land in the malformed bucket."""
    adapter = _adapter()
    for frame in json.loads(FIXTURE.read_text(encoding="utf-8"))["frames"]:
        adapter.normalise(frame["payload"])

    assert adapter.counters.malformed_payloads == 0
    assert adapter.counters.ticks == 5
    assert adapter.counters.non_tick_frames == 3  # prev_close, oi, status
    assert adapter.counters.untraded_frames == 1
    assert adapter.counters.exchange_time_fallbacks == 0, (
        "every tick in the fixture carries a reconstructable exchange timestamp"
    )


# ------------------------------------------------------ disconnect handling
def test_token_expiry_is_the_reason_code_that_needs_a_new_token():
    assert DISCONNECT_TOKEN_EXPIRED == 807
    assert DISCONNECT_REASONS[807] == "access token expired"
    for code in (805, 806, 808, 809):
        assert code in DISCONNECT_REASONS


def test_token_expired_is_false_until_dhan_says_so():
    adapter = _adapter()
    assert adapter.token_expired is False
    adapter.last_disconnect_code = 805
    assert adapter.token_expired is False
    adapter.last_disconnect_code = DISCONNECT_TOKEN_EXPIRED
    assert adapter.token_expired is True


def test_the_disconnect_probe_recovers_the_reason_code_the_sdk_only_prints():
    """2.2.0's ``server_disconnection`` prints the reason and returns None, so the
    code never reaches the caller — a token-expiry disconnect would be
    indistinguishable from an unknown frame, and reconnecting with the same dead
    token would loop forever."""
    import struct

    adapter = _adapter()
    calls: list[bytes] = []

    class _FakeFeed:
        def server_disconnection(self, data: bytes) -> None:
            calls.append(data)

    adapter._feed = _FakeFeed()
    adapter._install_disconnect_probe()

    frame = struct.pack("<BHBIH", 50, 10, 2, 0, DISCONNECT_TOKEN_EXPIRED)
    adapter._feed.server_disconnection(frame)

    assert adapter.last_disconnect_code == DISCONNECT_TOKEN_EXPIRED
    assert adapter.token_expired is True
    assert adapter.counters.disconnects == 1
    assert adapter.counters.disconnect_codes == {DISCONNECT_TOKEN_EXPIRED: 1}
    assert calls, "the SDK's own handler must still run"


def test_a_truncated_disconnect_frame_does_not_raise():
    adapter = _adapter()

    class _FakeFeed:
        def server_disconnection(self, data: bytes) -> None:
            return None

    adapter._feed = _FakeFeed()
    adapter._install_disconnect_probe()
    adapter._feed.server_disconnection(b"\x32")

    assert adapter.last_disconnect_code is None
    assert adapter.counters.disconnects == 0


# --------------------------------------------------------------- shutdown
def test_stop_uses_the_synchronous_close_not_the_coroutine():
    """Phase 1 called ``disconnect()``, a coroutine, so it built an un-awaited
    coroutine object and never closed the socket. ``close_connection()`` is the
    sync wrapper."""
    adapter = _adapter()
    closed: list[str] = []

    class _FakeFeed:
        def close_connection(self) -> None:
            closed.append("close_connection")

        async def disconnect(self) -> None:  # pragma: no cover - must not be called
            closed.append("disconnect")

    adapter._feed = _FakeFeed()
    adapter._running = True
    adapter.stop()

    assert closed == ["close_connection"]
    assert adapter.is_running is False


def test_stop_is_idempotent_and_survives_a_failing_close():
    adapter = _adapter()

    class _Angry:
        def close_connection(self) -> None:
            raise RuntimeError("socket already gone")

    adapter._feed = _Angry()
    adapter.stop()  # must not raise
    adapter.stop()  # second call has no feed at all


# ----------------------------------------------------------- resubscription
def test_resubscribe_all_sends_the_whole_set_not_the_delta():
    """A new socket carries none of the old subscriptions, while ``subscribe``
    deliberately sends only what is new."""
    adapter = _adapter()
    sent: list[list[tuple[int, str, int]]] = []

    class _FakeFeed:
        def subscribe_symbols(self, symbols: list[tuple[int, str, int]]) -> None:
            sent.append(symbols)

    adapter.subscribe(["49081", "13"])
    adapter._feed = _FakeFeed()
    adapter.resubscribe_all()

    assert len(sent) == 1
    assert {sid for _, sid, _ in sent[0]} == {"49081", "13"}


def test_resubscribing_with_no_subscriptions_is_a_no_op():
    adapter = _adapter()
    adapter._feed = object()  # would raise if touched
    adapter.resubscribe_all()


# --------------------------------------------------------- SDK isolation
def test_only_the_dhan_adapter_imports_the_sdk():
    """The spec's rule that strategies never call the SDK, enforced structurally.

    Phase 2 adds authentication, which speaks to Dhan over httpx rather than
    through the SDK's ``DhanLogin`` precisely so this stays a one-file rule.
    """
    result = subprocess.run(
        [
            "grep",
            "-rlnE",
            # Actual import statements, not mentions. Matching the bare word
            # would flag the docstrings that explain *why* auth avoids the SDK,
            # which is the opposite of the intended signal.
            r"^[[:space:]]*(import[[:space:]]+dhanhq|from[[:space:]]+dhanhq)",
            "--include=*.py",
            "common",
            "strategies",
            "runtimes",
            "dashboards",
            "scripts",
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    importers = {line for line in result.stdout.splitlines() if line}
    assert importers == {"common/market_data/dhan.py"}, (
        f"dhanhq must only be imported by the adapter, found: {sorted(importers)}"
    )


def test_the_sdk_is_not_imported_at_package_import_time():
    """A lazy import keeps credential-free test runs fast and offline."""
    code = (
        "import sys; import common.market_data.dhan; "
        "assert 'dhanhq' not in sys.modules, 'dhanhq imported eagerly'"
    )
    result = subprocess.run(
        [sys.executable, "-c", code], cwd=REPO_ROOT, capture_output=True, text=True, check=False
    )
    assert result.returncode == 0, result.stderr


def test_authentication_does_not_import_the_sdk():
    """DhanLogin exists in dhanhq 2.2.0; using it would breach the one-file rule."""
    code = (
        "import sys; import common.authentication; "
        "assert 'dhanhq' not in sys.modules, 'auth pulled in the SDK'"
    )
    result = subprocess.run(
        [sys.executable, "-c", code], cwd=REPO_ROOT, capture_output=True, text=True, check=False
    )
    assert result.returncode == 0, result.stderr


def test_the_fixture_contains_no_credential_or_account_identifier():
    raw = FIXTURE.read_text(encoding="utf-8")
    for forbidden in ("accessToken", "access_token", "dhanClientId", "pin", "totp"):
        assert forbidden not in raw, f"{forbidden} must never appear in a test fixture"
